- name: download KickStarterPy.git
  ansible.builtin.git:
    repo: 'https://{{token}}:{{token}}@github.com/HackingMoRe/KickStarterPy.git'
    dest: '/root/KickStarterPy'
    version: '2d55a1c65c35fcb8bca62ecccae05bcfe641a7e9'
    force: yes
    
- name: Install Python dependencies from requirements.txt
  ansible.builtin.pip:
    requirements: /root/KickStarterPy/requirements.txt
    #extra_args: --break-system-packages
  tags: pip

- name: install kickstarterpy configuration
  copy:
    src: ./configs/kickstarterpy.template.env
    dest: /root/KickStarterPy/.env

- name: add vulnbox_ip
  ansible.builtin.lineinfile:
    path: /root/KickStarterPy/.env
    search_string: "VULNBOX_IP="
    line: "VULNBOX_IP={{ vulnbox_ip }}"

- name: add packmate username
  ansible.builtin.lineinfile:
    path: /root/KickStarterPy/.env
    search_string: "PACKMATE_USERNAME="
    line: "PACKMATE_USERNAME=unimore"

- name: add packmate password
  ansible.builtin.lineinfile:
    path: /root/KickStarterPy/.env
    search_string: "PACKMATE_PASSWORD="
    line: "PACKMATE_PASSWORD={{ packmate_password }}"

- name: add packmate flag regex
  ansible.builtin.lineinfile:
    path: /root/KickStarterPy/.env
    search_string: "PACKMATE_FLAG_REGEX="
    line: "PACKMATE_FLAG_REGEX=[A-Za-z0-9]{31}="

- name: add base path
  ansible.builtin.lineinfile:
    path: /root/KickStarterPy/.env
    search_string: "LOCAL_BASE_PATH="
    line: "LOCAL_BASE_PATH={{ base_path }}"

- name: Ensure packmate_config.py is executable
  ansible.builtin.file:
    path: /root/KickStarterPy/packmate_config.py
    mode: '0755'

- name: Run packmate_config.py in foreground
  ansible.builtin.shell: |
    python3 packmate_config.py
  args:
    chdir: /root/KickStarterPy

- name: Ensure git_deploy is executable
  ansible.builtin.file:
    path: /root/KickStarterPy/git_deploy.py
    mode: '0755'

- name: Run git_deploy.py in foreground
  ansible.builtin.shell: |
    python3 git_deploy.py
  args:
    chdir: /root/KickStarterPy

- name: receive.denyCurrentBranch ignore
  ansible.builtin.shell: |
    git config --global receive.denyCurrentBranch ignore
  args:
    chdir: /root/KickStarterPy
 