- name: download wisscon
  ansible.builtin.git:
    repo: 'https://{{token}}:{{token}}@github.com/HackingMoRe/wisscon.git'
    dest: '/root/wisscon'
    version: '2d1bafb330f7a179f0ad11933cd423209f9bc87b'
    force: yes