version: "3.2"
services:
  mongo:
    image: mongo:5
    networks:
      - internal
    restart: always
    ports:
      - "127.0.0.1:27017:27017"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-frontend
    image: tulip-frontend:latest
    ports:
      - "31338:31338"
    depends_on:
      - mongo
    networks:
      - internal
    environment:
      API_SERVER_ENDPOINT: http://api:31339/
#      REACT_APP_TULIP_WEB_LOGIN: ${TULIP_WEB_LOGIN}
#      REACT_APP_TULIP_WEB_PASSWORD: ${TULIP_WEB_PASSWORD}

  api:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: tulip-api:latest
    ports:
      - "127.0.0.1:31339:31339"
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro
    environment:
      TULIP_MONGO: mongo:27017
      TULIP_TRAFFIC_DIR: ${TRAFFIC_DIR_DOCKER}
      FLAG_REGEX: ${FLAG_REGEX}
      TICK_START: ${TICK_START}
      TICK_LENGTH: ${TICK_LENGTH}

  assembler:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-assembler
    image: tulip-assembler:latest
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro
    command: "./assembler -dir ${TRAFFIC_DIR_DOCKER}"
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
      FLAG_REGEX: ${FLAG_REGEX}

  enricher:
    build:
      context: services/go-importer
      dockerfile: Dockerfile-enricher
    image: tulip-enricher:latest
    depends_on:
      - mongo
    networks:
      - internal
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro
    command: "./enricher -eve ${TRAFFIC_DIR_DOCKER}/eve.json"
    environment:
      TULIP_MONGO: ${TULIP_MONGO}
    restart: unless-stopped

  # Suricata is needed for sniffing traffic
  suricata:
    build:
      context: suricata
      dockerfile: Dockerfile-suricata
    volumes:
#      - /var/log/suricata:/var/log/suricata
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:rw
#      - /root/tulip/suricata/log:/var/log/suricata              # this is for suricata logs
#      - /root/tulip/suricata:/etc/suricata                      # this is for suricata config
    cap_add:
      - NET_RAW
      - NET_ADMIN
    privileged: true
    network_mode: "host"
    restart: unless-stopped


networks:
  internal:
