config_version: 1.33.7
github:
    token: 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
    email: gitburner+55997@starless.dev
contributors:
 - StarlessDev
 - gibait
 - salor02
 - ray3r
 - samucarpi
 - SamuMazzi
